<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="200"
    height="100%"
    viewBox="0 0 100 100"
    overflow="visible"
    fill="#ff7300"
    stroke="#ffffff"
  >
    <defs><polygon id="loader" points="20,40 28,55 12,55" /></defs>
    <use xlink:href="#loader" transform="rotate(30 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.08s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.08s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(60 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.17s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.17s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(90 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.25s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.25s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(120 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.33s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.33s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(150 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.42s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.42s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(180 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.50s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.50s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(210 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.58s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.58s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(240 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.67s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.67s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(270 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.75s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.75s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(300 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.83s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.83s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(330 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="0.92s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="0.92s"
        repeatCount="indefinite"
      ></animate>
    </use>
    <use xlink:href="#loader" transform="rotate(360 50 50)">
      <animateTransform
        attributeName="transform"
        type="scale"
        additive="sum"
        dur="1s"
        begin="1.00s"
        repeatCount="indefinite"
        from="0"
        to="1.2"
      ></animateTransform>
      <animate
        attributeName="opacity"
        values="0;1;0"
        dur="1s"
        begin="1.00s"
        repeatCount="indefinite"
      ></animate>
    </use>
  </svg>
</template>
